from .categoria import Categoria
from .cliente import Cliente
from .producto import Producto
from .marcas import Marca
from .inventario import Inventario
from .colores import Color
from .tallas import Talla
from .proveedores import Proveedor
from .empleados import Empleado
from .ventas import Venta
from .compras import Compra
from .detalle_ventas import DetalleVenta
from .detalle_compras import DetalleCompra
from .resenas import Resena
from .promociones import Promocion